name: Buid and test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Show SoftUni username
      run: echo "mitkogatev"
    - name: Checkout repo
      uses: actions/checkout@v3
    - name: Use Node.js 18.x
      uses: actions/setup-node@v3
      with:
        node-version: 18.x
        cache: 'npm'
    - name: Build
      run: npm install
    - name: Start Unit tests
      run: npm run test:unit
  # deploy:
  #     needs: build
  #     runs-on: ubuntu-latest
  #     steps:
  #       - name: Deploy to render
  #         uses: johnbeynon/render-deploy-action@v0.0.8
  #         with:
  #           service-id: ${{ secrets.MY_RENDER_SERVICE_ID }}
  #           api-key: ${{ secrets.MY_RENDER_API_KEY }}
  deploy:
    name: Wait for Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Wait for Render Deployment
        uses: bounceapp/render-action@0.6.0
        with:
          render-token: ${{ secrets.MY_RENDER_API_KEY }}
          # github-token: ${{ secrets.GITHUB_TOKEN }}
          service-id: ${{ secrets.MY_RENDER_SERVICE_ID }}
          retries: 20
          wait: 16000
          sleep: 30000
  run-ui-tests:
      needs: deploy
      runs-on: ubuntu-latest

      steps:
        - name: Repo checkout
          uses: actions/checkout@v3
        - name: Use Node.js 18.x
          uses: actions/setup-node@v3
          with:
            node-version: 18.x
            cache: "npm"
        - name: Install npm packages
          run: npm install
        - name: Install playwright
          run:  npx playwright install     
        - name: run UI tests
          run: npm run test:ui